#perform_audit()
#{
    echo
    echo "--- Performance audit start ---"
    echo
    echo "* Check MariaDB version"
    audit_mysql_command "select @@version" "version" ""
    echo "* Check InnoDB buffer pool size"
    audit_mysql_command "select CONVERT(@@innodb_buffer_pool_size /1024/1024/1024, INTEGER)" "InnoDB buffer pool size" "GB"
    echo "* Check available and installed memory"
    audit_ssh_command "(echo scale=0; cat /proc/meminfo  | egrep 'MemTotal|MemAvailable' | sort | tr -s ' ' | cut -d ' ' -f 2 | sed -e 's/$/\/1048576/g')  | bc  | tr '\n' ' ' | sed -re 's/^(.*)\ (.*)\ /\1 of \2 GB\n/'" "available memory"
    echo "* Check InnoDB log file size"
    audit_mysql_command "select CONVERT(@@innodb_log_file_size /1024/1024, INTEGER)" "InnoDB log file size" "MB"
    echo "* Check InnoDB log file number"
    audit_mysql_command "select @@innodb_log_files_in_group" "InnoDB log file number" "files"
    echo "* Check InnoDB flush method"
    audit_mysql_command "select @@innodb_flush_method" "InnoDB flush method" ""
    echo "* Check InnoDB I/O capacity"
    audit_mysql_command "select @@innodb_io_capacity" "InnoDB I/O capacity" "iops"
    echo "* Check thread cache size"
    audit_mysql_command "select @@thread_cache_size" "Thread cache size" "threads"
    echo "* Check threads_created counter"
    audit_mysql_show_command "show global status like 'threads_created'" "threads created" "threads" "Threads_created"
    echo "* Check table open cache size"
    audit_mysql_command "select @@table_open_cache" "Table open cache size" "tables"
    echo "* Check tables opened counter"
    audit_mysql_show_command "show global status like 'Opened_tables'" "tables opened" "tables" "Opened_tables"
    echo "* Check table definitions cache size"
    audit_mysql_command "select @@table_definition_cache" "Table definitions cache  size" "definitions"
    echo "* Check table definitions opened counter"
    audit_mysql_show_command "show global status like 'Opened_table_definitions'" "table definitions  opened" "definitions" "Opened_table_definitions"
    echo "* Check query cache is enabled"
    audit_mysql_command "select @@query_cache_type" "Query cache is enabled" ""
    echo "* Check query cache size"
    audit_mysql_command "select convert(@@query_cache_size /1024 /1024, INTEGER)" "Query cache size" "MB"
    echo "* Check query cache efficiency"
    audit_query_cache "" "Query cache efficiency" 
    echo "* Check max tmp table size"
    audit_mysql_command "select convert(@@tmp_table_size /1024 /1024, INTEGER)" "Max tmp table size" "MB"
    echo "* Check max memory table size"
    audit_mysql_command "select convert(@@max_heap_table_size /1024 /1024, INTEGER)" "Max memory table size" "MB"
    echo "* Check max connections"
    audit_mysql_command "select @@max_connections" "Max connections" "conns"
    echo "* Check max connections used counter"
    audit_mysql_show_command "show global status like 'Max_used_connections'" "max used connections" "conns" "Max_used_connections"
    echo "* Check InnoDB stats on metadata flag"
    audit_mysql_command "select @@innodb_stats_on_metadata" "InnoDB stats on metadata enabled" ""
    echo "* Check Linux I/O scheduler"
    audit_ssh_command 'for s in  /sys/block/*/queue/scheduler; do disk=$(echo $s | cut -d "/" -f 4); echo -n "   $disk: "; cat $s; done' "scheduler setting"
    echo "* Check Linux swappiness setting"
    audit_ssh_command "/sbin/sysctl vm.swappiness" "swappiness setting"
    echo "* Check Linux mount options"
    audit_ssh_command "mount | grep '^/'" "mount options"
    echo
    echo "--- Performance audit end ---"
    exit 0
#}
