---
- name: Check OS Metrics
  hosts: dbservers
  remote_user: root
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Check available and installed memory
      shell: 
        echo scale=0; cat /proc/meminfo  | egrep 'MemTotal|MemAvailable' | sort | tr -s ' '
      register: available_installed_mem
      tags: check_available_installed_mem

    - name: check IO scheduler settings
      shell: for s in  /sys/block/*/queue/scheduler; do disk=$(echo $s | cut -d "/" -f 4); echo -n "   $disk- "; cat $s; done
      register: io_scheduler_config
      tags: check_io_scheduler_settings

    - name: check linux swappiness setting
      shell: /sbin/sysctl vm.swappiness
      register: linuxx_swappiness
      tags: check_linux_swappiness_settings

    - name: check linux mount options
      shell: mount | grep '^/'
      register: mount_options
      tags: check_linux_mount_options
