---
- name: Check_Existing_DB_Service
  script: ./check_existing_db_service.sh
  register: db_service_check
  no_log: True
  tags: check_db_service

- name: Display_DB_Service_Status
  debug: 
    msg: "{{ db_service_check.stdout }}"
  when: db_service_check.stdout | length > 0
  tags: db_service_status

- name: Check DB version
  command: "mysql -BNe 'select @@version;'"
  register: mariadb_version
  tags: check_db_version

- name: write MariaDB version to file
  shell: |
    echo "* Check MariaDB version" >> {{ reportdir }}/dbVersion_{{ ansible_hostname }}
    echo "version for {{ ansible_hostname }} : {{ mariadb_version.stdout }} " >> {{ reportdir }}/dbVersion_{{ ansible_hostname }}
  register: file_written
  delegate_to: 127.0.0.1
  when: mariadb_version | length > 0

- name: echo report directory
  debug: msg="report written to file - {{ reportdir }}/dbVersion_{{ ansible_hostname }}"
  when: "file_written.rc == 0"
